version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: core/server.py
      FLASK_ENV: development
    command: bash run.sh
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flaskapp
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
